<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>

		<PackageId>PeterJuhasz.Repositories.InMemory</PackageId>
		<PackageTags>repositories;blobs;inmemory</PackageTags>
		<PackageProjectUrl>https://github.com/Peter-Juhasz/repos</PackageProjectUrl>
		<VersionPrefix>2.0.0</VersionPrefix>
		<RepositoryUrl>https://github.com/Peter-Juhasz/repos</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\PeterJuhasz.Repositories.Abstractions\PeterJuhasz.Repositories.Abstractions.csproj" />
	</ItemGroup>

</Project>
